### ISSUE TITLE
虎牙任务启动报错

### ISSUE THREAD

**Issue by wwkk2580** [nfe-w/aio-dynamic-push#21]
![image](https://github.com/nfe-w/aio-dynamic-push/assets/76099203/daa7e543-e745-4837-8b43-9fdaa1335777)

**Comment by nfe-w** [comment]
吃完午饭看一下

**Comment by wwkk2580** [comment]
> 吃完午饭看一下
````
  - name: 任务_huya
    enable: true
    type: huya
    intervals_second: 300
    begin_time: "00:00"
    end_time: "23:59"
    target_push_name_list:
      - 推送通道_钉钉机器人
    enable_living_check: true
    # 直播间号列表，用于检测开播状态，如果不开启直播检测可以不填
    room_id_list:
      - "163264"
      - "673958"
      - "499213"
`````
