### ISSUE TITLE
通知渠道能否支持自建的bark服务

### ISSUE THREAD

**Issue by goodryb** [nfe-w/aio-dynamic-push#45]
目前通知渠道的配置中，bark只有填写key的地方，应该用的是官方的服务

我这边是自建的bark，调用上一般是要通过自己的域名， 例如   http://myhost.com/key/********

建议增加一个配置域名的参数

**Comment by nfe-w** [comment]
已添加，重新拉取镜像即可
```yml
push_channel:
  - name: 推送通道_Bark
    enable: false
    type: bark
    # iOS 设备专用，Bark 服务器地址，如果启动该推送则必填，不要携带最后的"/"，默认值：https://api.day.app
    server_url: https://api.day.app
    # iOS 设备专用，Bark app 的key，如果启动该推送则必填
    key:
```
